// MultdarkCommandThread.java
// $Id$
package ngat.moptop;

import java.lang.*;
import java.text.*;
import java.util.*;

import ngat.moptop.command.*;
import ngat.util.logging.*;

/**
 * Utility class used by DARKImplementation and MULTDARKImplementation, 
 * to send multdark commands to an individual C layer, and monitor their results.
 * @author Chris Mottram
 * @version $Revision$
 */
public class MultdarkCommandThread extends Thread
{
	/**
	 * Revision Control System id string, showing the version of the Class.
	 */
	public final static String RCSID = new String("$Id$");
	/**
	 * A reference to the Moptop object. Used to access logging facilities.
	 * @see Moptop
	 */
	protected Moptop moptop = null;
	/**
	 * A reference to the Moptop status object. Used to access configuration properties.
	 * @see MoptopStatus
	 */
	protected MoptopStatus status = null;
	/**
	 * Which C layer we are interacting with.
	 */
	protected int cLayerIndex;
	/**
	 * The Multdark exposure length, in milliseconds.
	 */
	protected int exposureLength;
	/**
	 * How many exposures to do in a Multdark.
	 */
	protected int exposureCount;
	/**
	 * Return value from C layer: how many FITS files were produced.
	 */
	protected int filenameCount;
	/**
	 * Return value from C layer: The multdark number of the FITS files.
	 */
	protected int multdarkNumber;
	/**
	 * Return value from C layer: The last FITS filename produced.
	 */
	protected String lastFilename;
	/**
	 * The exception thrown by the Multdark Command, if an error occurs.
	 */
	protected Exception exception = null;
	
	/**
	 * Used to set the Moptop reference.
	 * @param m The Moptop reference.
	 * @see #moptop
	 */
	public void setMoptop(Moptop m)
	{
		moptop = m;
	}
	
	/**
	 * Used to set the Moptop status object reference.
	 * @param s The Moptop status object reference.
	 * @see #status
	 */
	public void setStatus(MoptopStatus s)
	{
		status = s;
	}
	
	/**
	 * Set the C layer index.
	 * @param i The index to use.
	 * @see #cLayerIndex
	 */
	public void setCLayerIndex(int i)
	{
		cLayerIndex = i;
	}
	
	/**
	 * Set the Multdark command parameters.
	 * @param expLen The exposure length in milliseconds.
	 * @param expCount The number of exposures.
	 * @see #exposureLength
	 * @see #exposureCount
	 */
	public void setMultdarkCommandParameters(int expLen,int expCount)
	{
		exposureLength = expLen;
		exposureCount = expCount;
	}
	
	/**
	 * The run method. This should be called after setCLayerIndex and setMultdarkCommandParameters have
	 * been called. sendMultdarkCommand is called, and if it throws an exception this is captured and
	 * stored in exception.
	 * @see #sendMultdarkCommand
	 * @see #exception
	 */
	public void run()
	{
		try
		{
			sendMultdarkCommand();
		}
		catch(Exception e)
		{
			exception = e;
		}
	}
	
	/**
	 * Get the last FITS image filename generated by the completed multdark command.
	 * @return A string containing the last FITS image filename generated by the completed multdark command.
	 * @see #lastFilename
	 */
	public String getLastFilename()
	{
		return lastFilename;
	}
	
	/**
	 * Get an exception thrown by the multdark command.
	 * @return The exception thrown as a result of the multdark command, or null if no exception occurred.
	 * @see #exception
	 */
	public Exception getException()
	{
		return exception;
	}
	
	/**
	 * Send the multdark command to the C layer.
	 * @exception Exception Thrown if an error occurs.
	 * @see #cLayerIndex
	 * @see #exposureLength
	 * @see #exposureCount
	 * @see #parseSuccessfulReply
	 * @see ngat.moptop.command.MultdarkCommand
	 * @see ngat.moptop.command.MultdarkCommand#setAddress
	 * @see ngat.moptop.command.MultdarkCommand#setPortNumber
	 * @see ngat.moptop.command.MultdarkCommand#setCommand
	 * @see ngat.moptop.command.MultdarkCommand#sendCommand
	 * @see ngat.moptop.command.MultdarkCommand#getParsedReplyOK
	 * @see ngat.moptop.command.MultdarkCommand#getReturnCode
	 * @see ngat.moptop.command.MultdarkCommand#getParsedReply
	 */
	protected void sendMultdarkCommand() throws Exception
	{
		MultdarkCommand command = null;
		int portNumber,returnCode;
		String hostname = null;
		String errorString = null;
		
		moptop.log(Logging.VERBOSITY_INTERMEDIATE,"sendMultdarkCommand:"+
			   "\n\t:cLayerIndex = "+cLayerIndex+
			   "\n\t:exposureLength = "+exposureLength+
			   "\n\t:exposureCount = "+exposureCount+".");
		command = new MultdarkCommand();
		// configure C comms
		hostname = status.getProperty("moptop.c.hostname."+cLayerIndex);
		portNumber = status.getPropertyInteger("moptop.c.port_number."+cLayerIndex);
		command.setAddress(hostname);
		command.setPortNumber(portNumber);
		moptop.log(Logging.VERBOSITY_INTERMEDIATE,"sendMultdarkCommand:cLayerIndex = "+cLayerIndex+
			   " :hostname = "+hostname+" :port number = "+portNumber+".");
		command.setCommand(exposureLength,exposureCount);
		// actually send the command to the C layer
		command.sendCommand();
		// check the parsed reply
		if(command.getParsedReplyOK() == false)
		{
			returnCode = command.getReturnCode();
			errorString = command.getParsedReply();
			moptop.log(Logging.VERBOSITY_TERSE,
				   "sendMultrunCommand:multdark command failed with return code "+
				   returnCode+" and error string:"+errorString);
			throw new Exception(this.getClass().getName()+
					    ":sendMultdarkCommand:Command failed with return code "+returnCode+
					    " and error string:"+errorString);
		}
		// extract data from successful reply.
		parseSuccessfulReply(command.getParsedReply());
		moptop.log(Logging.VERBOSITY_INTERMEDIATE,"sendMultdarkCommand:finished.");
	}
	
	/**
	 * Parse the successful reply string from the Multdark command.
	 * Currently should be of the form:
	 * "&lt;filename count&gt; &lt;multdark number&gt; &lt;last FITS filename&gt;".
	 * The preceeding '0' denoting success should have already been stripped off.
	 * @param replyString The reply string.
	 * @exception NumberFormatException Thrown if parsing the filename count or multdark number fails.
	 * @see #filenameCount
	 * @see #multdarkNumber
	 * @see #lastFilename
	 */
	protected void parseSuccessfulReply(String replyString) throws NumberFormatException
	{
		String token = null;
		StringTokenizer st = new StringTokenizer(replyString," ");
		int tokenIndex;
		
		moptop.log(Logging.VERBOSITY_VERBOSE,"parseSuccessfulReply:started.");
		tokenIndex = 0;
		while(st.hasMoreTokens())
		{
			// get next token 
			token = st.nextToken();
			moptop.log(Logging.VERBOSITY_VERY_VERBOSE,"parseSuccessfulReply:token "+
				   tokenIndex+" = "+token+".");
			if(tokenIndex == 0)
			{
				filenameCount = Integer.parseInt(token);
			}
			else if(tokenIndex == 1)
			{
				multdarkNumber = Integer.parseInt(token);
			}
			else if(tokenIndex == 2)
			{
				lastFilename = token;
			}
			else
			{
				moptop.log(Logging.VERBOSITY_VERBOSE,
					   "parseSuccessfulReply:unknown token index "+
					   tokenIndex+" = "+token+".");
			}
			// increment index
			tokenIndex++;
		}
		moptop.log(Logging.VERBOSITY_VERBOSE,"parseSuccessfulReply:finished.");
	}
}
